name = "mas"
type = "webpack"
account_id = "f9f566d62bc90a7eddfe669d50528453"
workers_dev = true
route = ""
zone_id = "2a671c9308d21548eb228e841e584ad2"

[site]
bucket = "dist"
entry-point = "workers-site"
